language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t epopevad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true epopevad/react-test npm test

after_success:
  - docker build -t epopevad/multi-client ./client
  - docker build -t epopevad/multi-nginx ./nginx
  - docker build -t epopevad/multi-server ./server
  - docker build -t epopevad/multi-worker ./worker

  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push epopevad/multi-client
  - docker push epopevad/multi-nginx
  - docker push epopevad/multi-server
  - docker push epopevad/multi-worker